### ISSUE TITLE
Breaks all SSL verification

### ISSUE THREAD

**Issue by lineargraph** [anderle02/attributemod#1]
This mod breaks all secure encrypted connections done by Minecraft. Please do not change the default socket connection. If you *must* use a trust all ssl context (rather than just shipping your own certificate), please only use that ssl context for your own requests. You make it quite easy for people to steal all kinds of info send by minecraft if on the same network, including the player session token (valid for 24h only, but still).

https://github.com/anderle02/attributemod/blob/5793dc295a3ac02a70687302f78dac8fa13d6841/src/main/java/dev/anderle/attributemod/api/PriceApi.java#L107-L129

**Comment by lineargraph** [comment]
I won't provide you with a fix for this (on account of this being a paid mod without a license that allows me to contribute), but this is not really something to be played around with.

**Comment by anderle02** [comment]
With my poor modding knowledge I just copied this function over from [here](https://stackoverflow.com/questions/2893819/accept-servers-self-signed-ssl-certificate-in-java-client) and didn't really question what it does, as other mods used that too.

Will be changed as soon as possible, I'll also create a license file so y'all can contribute.
Thanks a lot for making me aware of it :)
